version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PYTHONPATH=/code:/code/app  # Это решит проблему с core
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: sh -c "celery -A core worker -l info"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PYTHONPATH=/code:/code/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data: