# Generated by Django 5.0.3 on 2026-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('shipped', 'Доставлено'), ('canceled', 'Отменено')], default='pending', max_length=20),
        ),
    ]
